### ISSUE TITLE
STIX objects do not conform to STIX specification

### ISSUE THREAD

**Issue by kmsec-uk** [intel471/CU-GIR#1]
First of all thanks for publishing this!

Unfortunately The GIR STIX content does not conform to STIX standard - the timestamps are not in the format specified in STIX specification: https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_ksbm2nost85y

For example whilst attempting to parse the data with the stix2 library in Python:

```python
#!/usr/bin/env python3.11
import json
from stix2 import parse

with open("./intel471_cu-gir.json", "r") as gir_file:
    gir_json = json.load(gir_file)

for obj in gir_json:
    parse(obj, allow_custom=True)
```
You get the following error:

```
stix2.exceptions.InvalidValueError: Invalid value for Relationship 'created': must be a datetime object, date object, or timestamp string in a recognizable format.
```

I just wanted to check whether the implementation of your STIX processor is different from the standard, and is this a design choice? If so, I'll just work with the data as if it were regular JSON.

As an aside, for working with the stix2 library in Python this is a workaround (for the timestamp error - there are other STIX inconsistencies):

```python
#!/usr/bin/env python3.11
import json
from stix2 import parse
from datetime import datetime

with open("./intel471_cu-gir.json", "r") as gir_file:
    gir_json = json.load(gir_file)

updated_gir_json = []

for obj in  gir_json:
    updated_obj = {}
    for k, v in obj.items():
        if k in ("created", "modified"):
            parsed_invalid_date = datetime.strptime(v, "%d/%m/%Y %H:%M:%S")
            updated_obj[k] = parsed_invalid_date.strftime("%Y-%m-%dT%H:%M:%SZ")
        else:
            updated_obj[k] = v
    updated_gir_json.append(updated_obj)
```

**Comment by cmason471** [comment]
Hi,

Thanks for providing this feedback, it is very valuable and we always welcome input from the community. 

The timestamp issue is indeed an oversight on our behalf and not a design choice, I will correct this in the next release. Could you also please highlight any other inconsistencies you've discovered and i'll take a look at those at the same time?

Many thanks

**Comment by kmsec-uk** [comment]
Apologies in advance for the wall of text. Basically there are 5 issues to fix in order to meet spec:

* Timestamp issue (as above)
* Note requires `object_refs`
* Grouping requires `object_refs`
* AttackMapping requires valid `kill_chain_phases` objects
* Location requires at least one missing property

Details below

---

## Missing object_refs on Note and Grouping SDOs

The error I get when attempting to use the `stix2` `parse()` function on **note** or **grouping** SDOs is a missing object_refs:

### Note SDO

The STIX note SDO is defined here: https://docs.oasis-open.org/cti/stix/v2.1/csprd01/stix-v2.1-csprd01.html#_Toc16070651

Example input:

```JSON
{
    "type": "note",
    "spec_version": "2.1",
    "created": "2023-06-12T12:27:19Z",
    "modified": "2023-06-12T12:27:19Z",
    "id": "note--b07d9c57-8898-9256-9694-576a680520a7",
    "abstract": "GIR CoA 4.6 Notes",
    "content": "Output capacity and resiliency.",
    "object_refs": [],
    "x_gir_id": "coa-eei--course-of-action--4.6#0#1",
    "x_coa_uuid": "course-of-action--c116ff04-8f2e-1f58-9b13-18b0947c40d5",
    "x_deprecated": false
}
```

Error:

```
stix2.exceptions.MissingPropertiesError: No values for required properties for Note: (object_refs).
```

### Grouping SDO

The grouping SDO is defined here: https://docs.oasis-open.org/cti/stix/v2.1/csprd01/stix-v2.1-csprd01.html#_Toc16070627

Example input

```JSON
{
    "type": "grouping",
    "spec_version": "2.1",
    "created": "2022-10-27T12:06:44Z",
    "modified": "2022-10-27T12:06:44Z",
    "id": "grouping--73b19ebe-4533-4456-964d-d17118405cf7",
    "name": "1 - Malware",
    "description": "Malicious software that is purpose-built to disrupt, damage or gain unauthorized access to a computer system including the mechanisms for its development, production and delivery.",
    "context": "unspecified",
    "object_refs": [],
    "x_gir_id": "1",
    "x_deprecated": false
}
```

Error:

```
stix2.exceptions.MissingPropertiesError: No values for required properties for Grouping: (object_refs).
```

## Invalid kill_chain_phases value

kill_chain_phases is an *optional* element in STIX Attack Mapping SDO: https://docs.oasis-open.org/cti/stix/v2.1/csprd01/stix-v2.1-csprd01.html#_Toc16070618

Example input:

```JSON
{
    "type": "attack-pattern",
    "spec_version": "2.1",
    "created": "2022-10-27T12:06:44Z",
    "modified": "2022-10-27T12:06:44Z",
    "id": "attack-pattern--0ced0600-0606-df56-a893-0b289c550616",
    "name": "Command and control tactic",
    "description": "Techniques adversaries may use to communicate with systems under their control within a victim network. Adversaries commonly attempt to mimic normal, expected traffic to avoid detection. There are many ways an adversary can establish command and control with various levels of stealth depending on the victim\ufffds network structure and defenses. (source: Mitre ATT&CK)",
    "aliases": null,
    "kill_chain_phases": [
        "6"
    ],
    "external_references": [
        {
            "source_name": "mitre-attack",
            "description": "Command and Control",
            "url": "https://attack.mitre.org/tactics/TA0011",
            "external_id": "x-mitre-tactic--f72804c5-f15a-449e-a5da-2eecd181f813",
            "hashes": null
        }
    ],
    "x_gir_id": "5.2.10",
    "x_deprecated": false
}
```

Error:

```
Invalid value for AttackPattern 'kill_chain_phases': type object 'KillChainPhase' has no attribute '_type'
```

The `kill_chain_phases` object should comprise of objects like in the spec https://docs.oasis-open.org/cti/stix/v2.1/csprd01/stix-v2.1-csprd01.html#_Toc16070596

So in the above example it should be something like this (not sure if `command-and-control` is the commonly accepted way to reference this stage or if it's referenced in numerical form "6" or shorthand "c2"):

```JSON
"kill_chain_phases": [
    {
      "kill_chain_name": "lockheed-martin-cyber-kill-chain",
      "phase_name": "command-and-control"
    }
  ],
```

Or, since kill_chain_phases is optional, it could be omitted entirely.

## Location objects must have the properties 'region', 'country', or 'latitude' and 'longitude'

Location SDOs are defined here: https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_th8nitr8jb4k

Example input:

```JSON
{
    "type": "location",
    "spec_version": "2.1",
    "created": "2022-10-27T12:06:44Z",
    "modified": "2022-10-27T12:06:44Z",
    "id": "location--a1f9ca66-c33b-4159-973c-7bc9a4d24170",
    "name": "The Caribbean",
    "description": "",
    "latitude": null,
    "longitude": null,
    "precision": 0,
    "region": null,
    "country": null,
    "administrative_area": null,
    "city": null,
    "street_address": null,
    "postal_code": null,
    "x_gir_id": "6.2.9",
    "x_deprecated": false
}
```

Error:

```
Location objects must have the properties 'region', 'country', or 'latitude' and 'longitude'
```

The docs state *At least one of the following properties/sets of properties MUST be provided:*

* *region*
* *country*
* *latitude and longitude*

And I tested that simply populating the `region` element was sufficient to meet spec:

```python
location="""
{
    "type": "location",
    "spec_version": "2.1",
    "created": "2022-10-27T12:06:44Z",
    "modified": "2022-10-27T12:06:44Z",
    "id": "location--a1f9ca66-c33b-4159-973c-7bc9a4d24170",
    "name": "The Caribbean",
    "description": "",
    "latitude": null,
    "longitude": null,
    "precision": 0,
    "region": "The Caribbean",
    "country": null,
    "administrative_area": null,
    "city": null,
    "street_address": null,
    "postal_code": null,
    "x_gir_id": "6.2.9",
    "x_deprecated": false
}"""

# no error thanks to populated Caribbean
parse(location, allow_custom=True)
```

**Comment by cmason471** [comment]
Thanks again for the feedback, this is very valuable and they _should_ be relatively quick fixes. I'll work on getting these included into the next release.

**Comment by cmason471** [comment]
Hi,

I pushed a new release today that should address all of the issues highlighted above. Thanks again for reaching out, please let me know if you have any further issues.
